[package]
name = "lykoi_drive"
version = "0.1.0"
edition = "2024"
authors = ["parchii"]
description = "terrible opengl bindings"
repository = "https://github.com/wainggan/lykoi_drive"
license = "MIT"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
lykoi_gl = "0.0.0"

